# Generated by Django 4.2 on 2024-06-10 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='number_of_3',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Количество троек'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='number_of_4',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Количество четверок'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='number_of_5',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Количество пятерок'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='photo',
            field=models.ImageField(default='applicants_photos/default.jpg', upload_to='applicants_photos/', verbose_name='Фото лица, 3x4'),
        ),
    ]
