# Generated by Django 5.0.2 on 2024-04-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_applicant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('watching', 'Рассмотрение'), ('answered', 'Выдан ответ')], default='Рассмотрение', max_length=20, verbose_name='Дата окончания школы'),
        ),
    ]
