# Generated by Django 5.0.2 on 2024-04-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_applicant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('watching', 'Рассмотрение'), ('answered', 'Выдан ответ')], default='watching', max_length=20, verbose_name='Дата окончания школы'),
        ),
    ]
