# Generated by Django 4.2 on 2024-06-11 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_admission_number_of_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='FIS',
        ),
        migrations.RemoveField(
            model_name='document',
            name='certificate',
        ),
    ]
