# Generated by Django 5.0.2 on 2024-04-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_applicant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='time_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
