# Generated by Django 4.2 on 2024-06-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_document_fis_remove_document_certificate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'verbose_name': 'Абитуриент', 'verbose_name_plural': 'Абитуриенты'},
        ),
        migrations.AlterField(
            model_name='admission',
            name='application_status',
            field=models.CharField(choices=[('Рассмотрение', 'Рассмотрение'), ('Отказано', 'Отказано'), ('Принят', 'Принят'), ('Отправлен на заполнение', 'Отправлен на заполнение')], default='Рассмотрение', max_length=50, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('Рассмотрение', 'Рассмотрение'), ('Выдан ответ', 'Выдан ответ')], default='watching', max_length=20, verbose_name='Статус заявки'),
        ),
    ]
