# Generated by Django 5.0.4 on 2024-04-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_applicant_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], default='female', max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('watching', 'Рассмотрение'), ('answered', 'Выдан ответ')], default='watching', max_length=20, verbose_name='Статус заявки'),
        ),
    ]
