# Generated by Django 4.2 on 2024-06-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_applicant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='gender',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], default='Мужской', max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('Рассмотрение', 'Рассмотрение'), ('Выдан ответ', 'Выдан ответ')], default='Рассмотрение', max_length=20, verbose_name='Статус заявки'),
        ),
    ]
