# Generated by Django 5.0.4 on 2024-04-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_applicant_gender_alter_applicant_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.RemoveField(
            model_name='school',
            name='address',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='time_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата отправки'),
        ),
    ]
