# Generated by Django 5.0.4 on 2024-04-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_applicant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='consent',
            field=models.FileField(blank=True, null=True, upload_to='consents/', verbose_name='Согласие на обработку данных'),
        ),
    ]
