# Generated by Django 5.0.4 on 2024-04-25 10:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_applicant_consent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='parents',
        ),
        migrations.AddField(
            model_name='admission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата отправки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='parent',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.applicant', verbose_name='Ребёнок'),
        ),
    ]
