# Generated by Django 5.0.4 on 2024-04-25 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_applicant_parents_admission_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='FIS',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИС'),
        ),
        migrations.AlterField(
            model_name='document',
            name='INN',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='document',
            name='SNILS',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='СНИЛС'),
        ),
        migrations.AlterField(
            model_name='document',
            name='certificate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Свидетельство'),
        ),
        migrations.AlterField(
            model_name='document',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='document',
            name='issued_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='document',
            name='original_or_copy',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Оригинал или копия'),
        ),
        migrations.AlterField(
            model_name='document',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='document',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='main.applicant', verbose_name='Абитуриент'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='father_full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО отца'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='father_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон отца'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='mother_full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО матери'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон матери'),
        ),
    ]
