# Generated by Django 5.0.4 on 2024-04-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_document_fis_alter_document_inn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='photo',
            field=models.ImageField(blank=True, default='applicants_photos/default.jpg', null=True, upload_to='applicants_photos/', verbose_name='Фото'),
        ),
    ]
