# Generated by Django 5.0.4 on 2024-04-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_applicant_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='photo',
            field=models.ImageField(default='applicants_photos/default.jpg', upload_to='applicants_photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='document',
            name='original_or_copy',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Оригинал или копия'),
        ),
    ]
