# Generated by Django 5.0.4 on 2024-04-28 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_applicant_graduation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='graduation_date',
            field=models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default='Дата окончания школы', verbose_name='Дата окончания школы'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='school',
            field=models.ForeignKey(blank=True, default='Школа', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.school', verbose_name='Школа'),
        ),
    ]
