# Generated by Django 5.0.4 on 2024-04-28 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_applicant_graduation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.school', verbose_name='Школа'),
        ),
    ]
