# Generated by Django 5.0.4 on 2024-05-01 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_applicant_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='admission_date',
            field=models.DateField(auto_now=True, verbose_name='Дата поступления'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='application_in_gov_services',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Заявление в гос. услугах'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='application_status',
            field=models.CharField(choices=[('watching', 'Рассмотрение'), ('answered', 'Выдан ответ')], default='watching', max_length=50, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='average_score',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Средний балл'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.department', verbose_name='Отделение'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='documents_collected',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Документы забраны'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='internal_exam_conducted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Внутренний экзамен проведен'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='number_of_3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество троек'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='number_of_4',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество четверок'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='number_of_5',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество пятерок'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='out_of_budget',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Внебюджет'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='received_receipt',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Получил расписку'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='school',
            field=models.CharField(max_length=255, verbose_name='Школа'),
        ),
    ]
