# Generated by Django 5.0.4 on 2024-05-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_admission_admission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='application_status',
            field=models.CharField(choices=[('watching', 'Рассмотрение'), ('accepted', 'Принят')], default='watching', max_length=50, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='average_score',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=2, null=True, verbose_name='Средний балл'),
        ),
    ]
