# Generated by Django 5.0.4 on 2024-05-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_admission_application_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='average_score',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='Средний балл'),
        ),
    ]
