# Generated by Django 5.0.4 on 2024-05-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_admission_average_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='department',
        ),
        migrations.AddField(
            model_name='admission',
            name='department',
            field=models.ManyToManyField(blank=True, null=True, to='main.department', verbose_name='Отделение'),
        ),
    ]
