# Generated by Django 5.0.4 on 2024-05-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_admission_department_admission_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона студента'),
        ),
    ]
