# Generated by Django 5.0.4 on 2024-05-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_applicant_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='original_or_copy',
        ),
        migrations.AddField(
            model_name='admission',
            name='original_or_copy',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Оригинал или копия'),
        ),
    ]
