# Generated by Django 5.0.4 on 2024-05-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_document_original_or_copy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalexam',
            name='student',
        ),
        migrations.AddField(
            model_name='internalexam',
            name='student',
            field=models.ManyToManyField(related_name='internal_exam', to='main.applicant', verbose_name='Студент'),
        ),
    ]
