# Generated by Django 5.0.4 on 2024-05-03 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_internalexam_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internalexam',
            old_name='student',
            new_name='students',
        ),
    ]
