# Generated by Django 5.0.4 on 2024-05-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_rename_student_internalexam_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internalexam',
            options={'verbose_name': 'Журнал вступительных экзаменов', 'verbose_name_plural': 'Журналы вступительных экзаменов'},
        ),
        migrations.AlterField(
            model_name='internalexam',
            name='students',
            field=models.ManyToManyField(to='main.applicant', verbose_name='Студент'),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateTimeField(blank=True, verbose_name='Дата собеседования')),
                ('students', models.ManyToManyField(to='main.applicant', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Журнал собеседований',
                'verbose_name_plural': 'Журналы собеседований',
            },
        ),
    ]
