# Generated by Django 5.0.4 on 2024-05-07 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_admission_exam_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='applicant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='main.applicant', verbose_name='Абитуриент'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='application_status',
            field=models.CharField(choices=[('watching', 'Рассмотрение'), ('denied', 'Отказано'), ('accepted', 'Принят'), ('warn', 'Отправлен на заполнение')], default='watching', max_length=50, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='graduation_date',
            field=models.IntegerField(choices=[(2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default='Дата окончания школы', verbose_name='Дата окончания школы'),
        ),
    ]
