# Generated by Django 5.0.4 on 2024-05-21 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_admission_applicant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='applicant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='main.applicant', verbose_name='Абитуриент'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='graduation_date',
            field=models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024')], default=('2021', '2021'), max_length=20, verbose_name='Дата окончания школы'),
        ),
        migrations.AlterField(
            model_name='document',
            name='INN',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='document',
            name='SNILS',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='СНИЛС'),
        ),
        migrations.AlterField(
            model_name='internalexam',
            name='students',
            field=models.ManyToManyField(related_name='exam', to='main.applicant', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='main.applicant', verbose_name='Ребёнок'),
        ),
    ]
